title    FORGE Linux (x86_64, UEFI, copy to RAM)
sort-key 02-forge-ram
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/intel-ucode.img
initrd   /%INSTALL_DIR%/boot/amd-ucode.img
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux-zen.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% copytoram quiet loglevel=3 apparmor=1 security=apparmor zswap.enabled=0 mitigations=auto nowatchdog nmi_watchdog=0 rw
